import csv

# Data structure
data = [
    {"Category": "Open Enrollment Information", "Name": "No documents", "URL": "", "Type": "Document"},
    {"Category": "Enrollment Documents", "Name": "2025 Benefit Guide", "URL": "https://sfsc.sharepoint.com/:b:/r/Open%20Enrollment%20Documents/2025%20Benefit%20Guide.pdf?csf=1&web=1&e=K2EQK4", "Type": "Document"},
    {"Category": "Enrollment Documents", "Name": "2025 Comparison Chart FSA Limits", "URL": "https://sfsc.sharepoint.com/:b:/r/Open%20Enrollment%20Documents/2025%20Comparison%20Chart%20NEW%20FSA%20Limits%2012-16-2024.pdf?csf=1&web=1&e=5hylvb", "Type": "Document"},
    {"Category": "Enrollment Documents", "Name": "2025 Saving and Spending Guide FSA Limits", "URL": "https://sfsc.sharepoint.com/:b:/r/Open%20Enrollment%20Documents/2025%20Saving%20and%20Spending%20Guide%20NEW%20FSA%20Limits%2012-16-2024.pdf?csf=1&web=1&e=Jxfn4y", "Type": "Document"},
    {"Category": "Enrollment Documents", "Name": "Beneficiary for Terminal Leave Form", "URL": "https://sfsc.sharepoint.com/:b:/r/Open%20Enrollment%20Documents/Beneficiary%20for%20Terminal%20Leave%20Form.pdf?csf=1&web=1&e=8ESTPq", "Type": "Document"},
    {"Category": "Enrollment Documents", "Name": "Payroll Authorization Changes for Annuities", "URL": "https://sfsc.sharepoint.com/:b:/r/Open%20Enrollment%20Documents/Payroll%20Authorization%20Changes%20for%20Annuities-1.pdf?csf=1&web=1&e=es6L7Q", "Type": "Document"},
    {"Category": "Enrollment Documents", "Name": "Sick Leave Pool Appl (Only During Open Enrollment)", "URL": "https://sfsc.sharepoint.com/:b:/r/Open%20Enrollment%20Documents/Sick%20Leave%20Pool%20Appl%20(Only%20During%20Open%20Enrollment).pdf?csf=1&web=1&e=H5uuBW", "Type": "Document"},
    {"Category": "Information Videos", "Name": "LegalShield", "URL": "https://player.vimeo.com/video/402593265", "Type": "Video"},
    {"Category": "Benefit Documents", "Name": "Annual Retirement Benefits Guide", "URL": "https://sfsc.sharepoint.com/:b:/r/Benefit%20Documents/Annual-Retirement-Benefits-Guide.pdf?csf=1&web=1&e=MbZz5e", "Type": "Document"},
    {"Category": "Benefit Documents", "Name": "Medicare and You 2025", "URL": "https://sfsc.sharepoint.com/:b:/r/Benefit%20Documents/Medicare%20and%20You%202025.pdf?csf=1&web=1&e=pc61Yo", "Type": "Document"},
    {"Category": "Benefit Documents", "Name": "Medicare ready", "URL": "https://sfsc.sharepoint.com/:b:/r/Benefit%20Documents/medicare-ready.pdf?csf=1&web=1&e=UtnDl2", "Type": "Document"},
    {"Category": "Benefit Documents", "Name": "Social Security Basics For New workers", "URL": "https://sfsc.sharepoint.com/:b:/r/Benefit%20Documents/newworkers.pdf?csf=1&web=1&e=VFl2Tk", "Type": "Document"},
    {"Category": "Benefit Documents", "Name": "OMNI TSACG – Winter 2025 Employee Newsletter", "URL": "https://sfsc.sharepoint.com/:b:/r/Benefit%20Documents/OMNI%20TSACG%20-%20Winter-2025-Employee-Newsletter-reduced.pdf?csf=1&web=1&e=qj6gpf", "Type": "Document"},
    {"Category": "Benefit Documents", "Name": "Reduce financial stress flyer", "URL": "https://sfsc.sharepoint.com/:b:/r/Benefit%20Documents/reduce-financial-stress-flyer.pdf?csf=1&web=1&e=ggDWV9", "Type": "Document"},
    {"Category": "Benefit Documents", "Name": "Retirement Ready Workers-18-48", "URL": "https://sfsc.sharepoint.com/:b:/r/Benefit%20Documents/workers-18-48.pdf?csf=1&web=1&e=6n3vef", "Type": "Document"},
    {"Category": "Benefit Documents", "Name": "Retirement Ready Workers-49-60", "URL": "https://sfsc.sharepoint.com/:b:/r/Benefit%20Documents/workers-49-60.pdf?csf=1&web=1&e=iVxh3f", "Type": "Document"},
    {"Category": "Benefit Documents", "Name": "Retirement Ready Workers-61-69", "URL": "https://sfsc.sharepoint.com/:b:/r/Benefit%20Documents/workers-61-69.pdf?csf=1&web=1&e=qgZ8vS", "Type": "Document"},
    {"Category": "Benefit Documents", "Name": "Retirement Ready Workers-70-Up", "URL": "https://sfsc.sharepoint.com/:b:/r/Benefit%20Documents/workers-70andup.pdf?csf=1&web=1&e=Gk7y4g", "Type": "Document"},
    {"Category": "Benefit Links", "Name": "MyBlueService (BCBSFL)", "URL": "https://www.floridablue.com/", "Type": "Link"},
    {"Category": "Benefit Links", "Name": "MyFRS", "URL": "https://www.myfrs.com/", "Type": "Link"},
    {"Category": "Benefit Links", "Name": "Learn how to Transition into Medicare", "URL": "https://sfsc.sharepoint.com/SiteCollectionDocuments/Learn%20how%20To%20Transtion%20into%20Medicare%20%20%20Flyer.pdf", "Type": "Link"},
    {"Category": "Benefit Links", "Name": "PeopleFirst", "URL": "https://peoplefirst.myflorida.com/", "Type": "Link"},
    {"Category": "Benefit Links", "Name": "MyBenefits", "URL": "https://www.mybenefits.myflorida.com/", "Type": "Link"},
    {"Category": "Benefit Links", "Name": "State Benefits YouTube", "URL": "https://www.youtube.com/channel/UCLaBCMnY1wK8bvcASEi_oWQ/videos", "Type": "Link"},
    {"Category": "Benefit Links", "Name": "Medicare Assistance", "URL": "https://shinema.org/", "Type": "Link"},
    {"Category": "Benefit Links", "Name": "OMNI and TSACG", "URL": "https://www.tsacg.com/individual/plan-sponsor/florida/south-florida-state-college/", "Type": "Link"},
    {"Category": "Employee Resources", "Name": "Credentialed Faculty List", "URL": "https://sfsc.sharepoint.com/sites/pod/_layouts/15/DocIdRedir.aspx?ID=D2MNHADY7Q74-3-72", "Type": "Document"},
    {"Category": "Employee Resources", "Name": "Political Campaign Related Activities", "URL": "https://sfsc.sharepoint.com/sites/pod/SiteCollectionDocuments/Political%20Campaign-Related%20Activities.pdf", "Type": "Document"},
    {"Category": "Employee Resources", "Name": "Salary Schedule", "URL": "https://sfsc.sharepoint.com/:b:/r/sites/pod/SiteCollectionDocuments/Salary Schedule.pdf?csf=1&web=1&e=6hgRWB", "Type": "Document"},
    {"Category": "Employee Resources", "Name": "Employee Handbook", "URL": "https://sfsc.sharepoint.com/sites/pod/SiteCollectionDocuments/Forms/AllItems.aspx?id=%2Fsites%2Fpod%2FSiteCollectionDocuments%2FEmployee%20Handbook%2Epdf&parent=%2Fsites%2Fpod%2FSiteCollectionDocuments", "Type": "Document"},
    {"Category": "Employee Resources", "Name": "Professional Standards for Faculty and Academic Administrators", "URL": "https://sfsc.sharepoint.com/:b:/s/pod/Eb43IMYcSw5ImAayHMxkQOIB2JEFipCot_roLmgOytgR_g?e=cp7YvT", "Type": "Document"},
    {"Category": "Employee Resources", "Name": "SafeColleges Login", "URL": "https://southflorida-fl.safecolleges.com/login", "Type": "Link"},
    {"Category": "Employee Resources", "Name": "Approved Driving List", "URL": "https://sfsc.sharepoint.com/:x:/r/sites/pod/SiteCollectionDocuments/Approved Driving List.xlsx?d=wff0b30e2ad19426aa91150461eed2a06&csf=1&web=1&e=OIo0kl", "Type": "Document"},
    {"Category": "Employee Resources", "Name": "Duty Days and Holidays Schedule 2024-2025", "URL": "https://sfsc.sharepoint.com/:x:/r/sites/pod/SiteCollectionDocuments/Duty Days and Holiday Schedule 2024-2025.xlsx?d=wc2158afdaf3c407a9736d5673a5c4f3b&csf=1&web=1&e=1WQwo1", "Type": "Document"},
    {"Category": "Employee Resources", "Name": "Code of Ethics", "URL": "https://sfsc.sharepoint.com/:b:/r/SiteCollectionDocuments/Code of Ethics 2021 Guide.pdf?csf=1&web=1&e=zweJep", "Type": "Document"},
    {"Category": "Employee Resources", "Name": "Duty Days and Holidays Schedule 2025-2026", "URL": "https://sfsc.sharepoint.com/:x:/s/pod/Ebt5v6L3sjZDsto5tcfdfG8BDRUGIkK4MGaahrEmXBp8sQ?e=gMh1OR", "Type": "Document"},
    {"Category": "Employee Resources", "Name": "Organizational Chart", "URL": "https://sfsc.sharepoint.com/:b:/s/pod/EdOEStNkpOtErdG70LyolYMBnrC9EK-FsOAscx3ATctX-g?e=BImFUk", "Type": "Document"},
    {"Category": "Wellness", "Name": "2025 Acentra Health EAP Brochure", "URL": "https://sfsc.sharepoint.com/:b:/r/Wellness/2025%20Acentra%20Health%20EAP%20Brochure.pdf?csf=1&web=1&e=Rhszen", "Type": "Document"},
    {"Category": "Wellness", "Name": "A 30-Day-Sleep-Challenge", "URL": "https://sfsc.sharepoint.com/:b:/r/Wellness/A%2030-Day-Sleep-Challenge.pdf?csf=1&web=1&e=y4JkB4", "Type": "Document"},
    {"Category": "Wellness", "Name": "Teladoc Health Info", "URL": "https://sfsc.sharepoint.com/:b:/r/Wellness/Teladoc%20Health%20Info.pdf?csf=1&web=1&e=mgEAQx", "Type": "Document"},
    {"Category": "Wellness", "Name": "Wellness Newsletter Jan-Feb-Mar 2025", "URL": "https://sfsc.sharepoint.com/:b:/r/Wellness/Wellness%20Newsletter%20Jan-Feb-Mar%202025.pdf?csf=1&web=1&e=C80tvy", "Type": "Document"},
    {"Category": "EAP Information", "Name": "2025 Acentra Health EAP Brochure", "URL": "https://sfsc.sharepoint.com/:b:/r/EAP%20Information/2025%20Acentra%20Health%20EAP%20Brochure.pdf?csf=1&web=1&e=tzk7Oa", "Type": "Document"},
    {"Category": "EAP Information", "Name": "Acentra Health Wallet Cards - SOF Colleges Universities", "URL": "https://sfsc.sharepoint.com/:b:/r/EAP%20Information/Acentra%20Health%20Wallet%20Cards%20-%20SOF%20Colleges%20%20Universities.pdf?csf=1&web=1&e=PU55CS", "Type": "Document"},
    {"Category": "EAP Information", "Name": "April 2025 Eating Right on the Run Tip Sheet - SOF Joinders", "URL": "https://sfsc.sharepoint.com/:b:/r/EAP%20Information/April%202025%20Eating%20Right%20on%20the%20Run%20Tip%20Sheet%20-%20SOF%20Joinders.pdf?csf=1&web=1&e=HkSXhF", "Type": "Document"},
    {"Category": "EAP Information", "Name": "EAP Products and Services – Florida", "URL": "https://sfsc.sharepoint.com/:b:/r/EAP%20Information/EAP%20Products%20and%20Services%20-%20Florida.pdf?csf=1&web=1&e=bPqcKB", "Type": "Document"},
    {"Category": "EAP Information", "Name": "Mar. 2025 Cultivating Compassion Tip Sheet - 800-607-1522 Sunshine", "URL": "https://sfsc.sharepoint.com/:b:/r/EAP%20Information/Mar.%202025%20Cultivating%20Compassion%20Tip%20Sheet%20-%20800-607-1522%20Sunshine-1.pdf?csf=1&web=1&e=dtxRMw", "Type": "Document"},
    {"Category": "EAP Information", "Name": "Q1 2025 Balance - State of Florida Universities & Colleges", "URL": "https://sfsc.sharepoint.com/:b:/r/EAP%20Information/Q1%202025%20Balance%20-%20State%20of%20Florida%20Universities%20%26%20Colleges.pdf?csf=1&web=1&e=JynUn6", "Type": "Document"},
    {"Category": "Performance Review", "Name": "Administrative Annual Evaluation", "URL": "https://sfsc.sharepoint.com/sites/pod/Forms/Administrative%20Annual%20Evaluation.pdf", "Type": "Document"},
    {"Category": "Performance Review", "Name": "Annual Service Report", "URL": "https://sfsc.sharepoint.com/sites/pod/Forms/Annual%20Service%20Report.pdf", "Type": "Document"},
    {"Category": "Performance Review", "Name": "Career Staff Annual Evaluation", "URL": "https://sfsc.sharepoint.com/sites/pod/Forms/Career%20Staff%20Annual%20Evaluation.pdf", "Type": "Document"},
    {"Category": "Performance Review", "Name": "Faculty Chair and Program Manager Annual Evaluation", "URL": "https://sfsc.sharepoint.com/sites/pod/Forms/Faculty%20Chair%20and%20Program%20Manager%20Annual%20Evaluation.pdf", "Type": "Document"},
    {"Category": "Performance Review", "Name": "Instructional Faculty Annual Evaluation", "URL": "https://sfsc.sharepoint.com/sites/pod/_layouts/15/DocIdRedir.aspx?ID=D2MNHADY7Q74-4-110", "Type": "Document"},
    {"Category": "Performance Review", "Name": "Classroom Observation Procedure and Form", "URL": "https://sfsc.sharepoint.com/SiteCollectionDocuments/Classroom%20Observation%20Procedure%20and%20Form.docx", "Type": "Document"},
    {"Category": "Performance Review", "Name": "Non-Instructional Faculty Annual Evaluation", "URL": "https://sfsc.sharepoint.com/sites/pod/Forms/Non-Instructional%20Faculty%20Annual%20Evaluation.pdf", "Type": "Document"},
    {"Category": "Performance Review", "Name": "President's Professional Staff Annual Evaluation", "URL": "https://sfsc.sharepoint.com/sites/pod/Forms/President's%20Professional%20Staff%20Annual%20Evaluation.pdf", "Type": "Document"},
    {"Category": "Performance Review", "Name": "Professional Staff Annual Evaluation", "URL": "https://sfsc.sharepoint.com/sites/pod/Forms/Professional%20Staff%20Annual%20Evaluation.pdf", "Type": "Document"},
    {"Category": "Performance Review", "Name": "Administrative Procedure 5040", "URL": "https://sfsc.sharepoint.com/sites/pod/_layouts/15/DocIdRedir.aspx?ID=D2MNHADY7Q74-6-240", "Type": "Document"},
    {"Category": "Performance Review", "Name": "Administrative Procedure 5041", "URL": "https://sfsc.sharepoint.com/sites/pod/_layouts/15/DocIdRedir.aspx?ID=D2MNHADY7Q74-6-241", "Type": "Document"},
]

# Write to CSV
with open("hr_resources.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=["Category", "Name", "URL", "Type"])
    writer.writeheader()
    writer.writerows(data)

print("CSV file 'hr_resources.csv' created successfully.")